name: HashBitStudio

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted #important

    strategy:
      matrix:
        node-version: [20.13.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/\
    env:
      NEXT_PUBLIC_API_BASE_URL: ${{secrets.NEXT_PUBLIC_API_BASE_URL}}
      NEXT_PUBLIC_BACKEND_API_KEY: ${{secrets.NEXT_PUBLIC_BACKEND_API_KEY}}
      RESEND_API_KEY: ${{secrets.RESEND_API_KEY}}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - name: Change Directory
        run: cd /home/safwan-hbs/actions-runner/_work/HBS-2.0/HBS-2.0/
      - run: pm2 restart 0
    #- 0 means HBS FE
